#!/bin/bash

####created by jmbarros at tech4it.com.br                              ##### 
####free to distributing, just give me some credits, okay ? :)         #####
###########################################################################

yum install keepalived haproxy -y

etc/init.d/keepalived start

chkconfig keepalived on